export const urls = {
	//baseUrl: "http://136.243.115.134:5000/api/",
	baseUrl: "http://localhost:60815/api/",
	getToken: "User/Token",
	checkEmailAvailability: "User/CheckEmailAvailability/",
	userRegistration: "User",
	organizationsList: "Organization",
	organizationTypesList: "OrganizationType",
	userNotificationsList: "Notification",
	userAccountActivation: "User/ActivateAccount/",
	searchOrganizations: "Organization/",
	getOrganization: "Organization/GetById/",
	organizationUrl: "Organization",
	locationUrl: "Location",
	getLocation: "Location/GetById/",
	sectorTypesUrl: "SectorTypes",
	getSectorType: "SectorTypes/GetById/",
	sectorCategoriesUrl: "SectorCategory",
	getSectorCategory: "SectorCategory/GetById/",
	sectorSubCategoriesUrl: "SectorSubCategory",
	getSectorSubCategory: "SectorSubCategory/GetById/",
	sectorsUrl: "Sector",
	getSector: "Sector/GetById/",
	projectTypesUrl: "ProjectType",
	getProjectType: "ProjectType/GetById/",
	projectsUrl: "Project",
	getProject: "Project/GetById/",
};